server:
  port: 8080
spring:
  application:
    name: "transfer-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapter:
  alfaservice:
    timeout: ${ALFA_TIMEOUT:5000}
    url: "${ALFA_TIMEOUT:http://localhost:3001/alfa/api/notification}"
  betaservice:
    timeout: ${BETA_TIMEOUT:5000}
    url: "${BETA_TIMEOUT:http://localhost:3002/beta/api/message}"

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      sendNotification:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s
        slidingWindowSize: 100
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 30s

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
